### ISSUE TITLE
KeyError: 'val1' in Atom when initializing (most) levels

### ISSUE THREAD

**Issue by jayelm** [alfworld/alfworld#21]
Hi, thanks for the great work!

Getting an error (occurs most, but not all of the time; seems level-dependent) when setting up alfworld according to instructions and running `alfworld-play-tw`:

```
Playing '/home/muj/.cache/alfworld/json_2.1.1/train/pick_and_place_with_movable_recep-Pen-Mug-Shelf-303/trial_T20190908_141515_537433'.
Traceback (most recent call last):
  File "/data/muj/miniconda3/envs/alfworld/bin/alfworld-play-tw", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data2/muj/alfworld/scripts/alfworld-play-tw", line 100, in <module>
    main(args)
  File "/data2/muj/alfworld/scripts/alfworld-play-tw", line 59, in main
    obs, infos = env.reset()
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/gym/envs/textworld.py", line 62, in reset
    obs, infos = super().reset()
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/gym/envs/textworld_batch.py", line 132, in reset
    self.batch_env.load(gamefiles)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/envs/batch/batch_env.py", line 209, in load
    env.load(game_file)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/core.py", line 317, in load
    return self._wrapped_env.load(path)
  File "/data2/muj/alfworld/scripts/alfworld-play-tw", line 25, in load
    super().load(*args, **kwargs)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/core.py", line 317, in load
    return self._wrapped_env.load(path)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/core.py", line 317, in load
    return self._wrapped_env.load(path)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/envs/wrappers/generic.py", line 22, in load
    self._wrap(textworld.start(gamefile, self.infos))
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/helpers.py", line 53, in start
    env.load(path)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/envs/pddl.py", line 54, in load
    self._state = State(self.downward_lib, data["pddl_problem"], self._logic)
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/logic/pddl_logic.py", line 234, in __init__
    facts = [atom.get_fact(self.name2type) for atom in atoms]
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/logic/pddl_logic.py", line 234, in <listcomp>
    facts = [atom.get_fact(self.name2type) for atom in atoms]
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/logic/pddl_logic.py", line 123, in get_fact
    arguments = [Variable(get_var_name(arg), name2type[arg]) for arg in args if arg]
  File "/data/muj/miniconda3/envs/alfworld/lib/python3.9/site-packages/textworld/logic/pddl_logic.py", line 123, in <listcomp>
    arguments = [Variable(get_var_name(arg), name2type[arg]) for arg in args if arg]
KeyError: 'val1'
```

it seems like in the `Atom` class, `self.name` is `Atom dummy(val1)`, which is then parsed into `args`, and there is no `val1` argument in the `name2type` dict.

Any idea what's going on here?

**Comment by MohitShridhar** [comment]
@jayelm, this error indicates that the task is unsolvable in Textworld. `movable_recep...` are tasks from ALFRED which involves carrying an object with another object like an apple in a bowl. We didn't add these tasks in ALFWorld because it made the Textworld engine super slow. When you try to load this in Textworld, the engine cannot construct a PDDL problem because "movable objects" are undefined in the domain description. 

Thanks for pointing this out! I'll add a note about this somewhere in the README.

**Comment by jayelm** [comment]
thanks @MohitShridhar !
