### ISSUE TITLE
BrokenPipeError when running a script

### ISSUE THREAD

**Issue by namsophi** [alfworld/alfworld#24]
Hello, 

I was trying to run ` python scripts/train_dagger.py configs/base_config.yaml`, but then I would get this error:

Traceback (most recent call last):
  File "scripts/train_dagger.py", line 448, in <module>
    train()
  File "scripts/train_dagger.py", line 87, in train
    if config["general"]["wandb"]:
KeyError: 'wandb'
Exception ignored in: <bound method Environment.__del__ of <textworld.envs.batch.batch_env.AsyncBatchEnv object at 0x7fc5ba44d358>>
Traceback (most recent call last):
  File "/Users/xxxx/opt/anaconda3/envs/yyyyyy/lib/python3.6/site-packages/textworld/core.py", line 260, in __del__
    self.close()
  File "/Users/xxxx/opt/anaconda3/envs/yyyyyy/lib/python3.6/site-packages/textworld/envs/batch/batch_env.py", line 184, in close
    env.call("close")
  File "/Users/xxxx/opt/anaconda3/envs/yyyyyy/lib/python3.6/site-packages/textworld/envs/batch/batch_env.py", line 61, in call
    self._pipe.send(("call", method, args))
  File "/Users/xxxx/opt/anaconda3/envs/yyyyyy/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/xxxx/opt/anaconda3/envs/yyyyyy/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/Users/xxxx/opt/anaconda3/envs/yyyyyy/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

The last section after the "Exception ignored in..." repeats on. Do you have any suggestions on what I could do to resolve this issue? Thanks in advance!

**Comment by MarcCote** [comment]
Hi! Is it possible you tried to modify `train_dagger.py` to report to WanDB? From your error message, it seems that `wandb` is not included in your config file under the `general` section.

See original config file: https://github.com/alfworld/alfworld/blob/master/configs/base_config.yaml#L41

**Comment by namsophi** [comment]
Hey @MarcCote , thanks, adding that one line solved my issue. :)
