### ISSUE TITLE
AssertionError: Invalid DISPLAY :0 - cannot find X server with xdpyinfo

### ISSUE THREAD

**Issue by Larerr** [alfworld/alfworld#39]
When I run ```python scripts/alfworld-play-thor```,  the code reports the following error, what should I do to solve the problem. 
Thanks!!!!!!

```python
Playing './json_2.1.1/train/pick_two_obj_and_place-Mug-None-Cabinet-318/trial_T20190910_055356_172564'.
No protocol specified
xdpyinfo:  unable to open display ":0".
Traceback (most recent call last):
  File "scripts/alfworld-play-thor", line 109, in <module>
    main(args)
  File "scripts/alfworld-play-thor", line 43, in main
    env = ThorEnv()
  File "/home/hongbo.wang/miniconda3/envs/alfworld/lib/python3.6/site-packages/alfworld/env/thor_env.py", line 39, in __init__
    player_screen_width=player_screen_width)
  File "/home/hongbo.wang/miniconda3/envs/alfworld/lib/python3.6/site-packages/ai2thor/controller.py", line 855, in start
    self.check_x_display(env['DISPLAY'])
  File "/home/hongbo.wang/miniconda3/envs/alfworld/lib/python3.6/site-packages/ai2thor/controller.py", line 715, in check_x_display
    ("Invalid DISPLAY %s - cannot find X server with xdpyinfo" % x_display)
AssertionError: Invalid DISPLAY :0 - cannot find X server with xdpyinfo
```

**Comment by MohitShridhar** [comment]
@Larerr have you started the xserver? See [this guide](https://github.com/alfworld/alfworld#cloud-instance)

You can check if the xserver by running `DISPLAY=:0 glxgears`. If it's printing the frame-rate, then it's working.

**Comment by MarcCote** [comment]
@Larerr any updates on this?

**Comment by LightCheat** [comment]
hi,my english is very bad.Please use translation software to translate the following sentence.
你可以使用mohitshridhar的办法,如果没有输出的话,请尝试更改 DISPLAY=: 后面的数值,我是修改成1之后,发现有了输出.
然后将alfworld/env/thor_env.py文件更改self.start(x_display='1',# x_display=x_display,

**Comment by MarcCote** [comment]
Thanks for the suggested fix. Here's the translation for reference.

> You can use the @MohitShridhar  method, if there is no output, please try to change the value DISPLAY=: after I changed it to 1, I found that there is an output. Then in the alfworld/env/thor_env.py file, change `self.start(x_display='1',# x_display=x_display`

**Comment by BatmanofZuhandArrgh** [comment]
Personallly I just change X_display = '1' in gen/constant.py.
