### ISSUE TITLE
Stuck at Quickstart when “pip install -e .[full]"

### ISSUE THREAD

**Issue by shi-xiaoli** [alfworld/alfworld#46]
Hi, thank you for your great work.
I was trying to install with pip using` pip install -e .[full]` when it was stuck.

```
Checking if build backend supports build_editable ... done
Building wheels for collected packages: textworld
    Building wheel for textworld (setup.py) ...  |
```
After several hours, the installation failed. The output is:
```
       31 22.1M   31 7078k    0     0   1951      0  3:18:50  1:01:53  2:16:57     0
       31 22.1M   31 7078k    0     0   1951      0  3:18:50  1:01:54  2:16:56     0
       31 22.1M   31 7078k    0     0   1950      0  3:18:56  1:01:55  2:17:01     0
       31 22.1M   31 7078k    0     0   1950      0  3:18:56  1:01:56  2:17:00     0
       31 22.1M   31 7078k    0     0   1949      0  3:19:02  1:01:57  2:17:05     0
      curl: (56) Recv failure: Connection timed out
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-kh7vysp_/setup.py", line 41, in <module>
          setup(
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-kh7vysp_/setup.py", line 37, in run
          _pre_install(None)
        File "/tmp/pip-req-build-kh7vysp_/setup.py", line 18, in _pre_install
          check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
        File "/media/hdd/sxl/miniconda3/envs/alfworld-py3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 56.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textworld
  Running setup.py clean for textworld
Failed to build textworld
ERROR: Could not build wheels for textworld, which is required to install pyproject.toml-based projects
```

Do you have any idea why?

**Comment by MarcCote** [comment]
Looks like it fails to download inform7. Can you try this from a terminal? (What OS are you running?)

    curl -LO http://emshort.com/inform-app-archive/6M62/I7-6M62-OSX-Interim.dmg

**Comment by MarcCote** [comment]
Actually, did you try running the pip install again? It might be a network glitch.

**Comment by shi-xiaoli** [comment]
> Actually, did you try running the pip install again? It might be a network glitch.

Thank you for your help. It does seem to be a network issue. I tried several times yesterday and failed，but it finally worked just now.

**Comment by MarcCote** [comment]
Thanks for letting us know.
