### ISSUE TITLE
Could not build wheels for textworld, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by OrilinZ** [alfworld/alfworld#77]
When I pip install alfworld, I faced the below problem:

`Building wheels for collected packages: textworld, visdom
  Building wheel for textworld (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for textworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [204 lines of output]
      /tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      /tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      /tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `description` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `description = 'Microsoft Textworld - A Text-based Learning Environment.'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `description` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `description` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `authors` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `authors = 'Microsoft Textworld'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `authors` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `authors` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py:72: _MissingDynamic: `classifiers` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `classifiers = ['Development Status :: 5 - Production/Stable', 'Intended Audience :: Developers', 'Intended Audience :: Information Technology', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Operating System :: MacOS', 'Operating System :: POSIX', 'Programming Language :: Python :: 3.9', 'Programming Language :: Python :: 3.10', 'Programming Language :: Python :: 3.11', 'Programming Language :: Python :: 3.12', 'Topic :: Scientific/Engineering :: Artificial Life']`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `classifiers` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `classifiers` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      running bdist_wheel
      running build
      running build_py
      + echo 'Running setup.sh...'
      Running setup.sh...
      ++ uname -s
      + unameOut=Linux
      + case "${unameOut}" in
      + machine=Linux
      + cd textworld/thirdparty/
      + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
      + echo 'Downloading Inform7 CLI'
      Downloading Inform7 CLI
      + curl -LO http://emshort.com/inform-app-archive/6M62/I7_6M62_Linux_all.tar.gz
        % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                       Dload  Upload   Total   Spent    Left  Speed
      
        0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        0 22.1M    0 46352    0     0  28612      0  0:13:33  0:00:01  0:13:32 28594
        3 22.1M    3  899k    0     0   337k      0  0:01:07  0:00:02  0:01:05  336k
       26 22.1M   26 6026k    0     0  1620k      0  0:00:14  0:00:03  0:00:11 1620k
       60 22.1M   60 13.4M    0     0  2996k      0  0:00:07  0:00:04  0:00:03 2996k
       88 22.1M   88 19.6M    0     0  3560k      0  0:00:06  0:00:05  0:00:01 3976k
      100 22.1M  100 22.1M    0     0  3837k      0  0:00:05  0:00:05 --:--:-- 5270k
      + '[' Linux == Mac ']'
      + '[' '!' -d inform7-6M62 ']'
      + tar xf I7_6M62_Linux_all.tar.gz
      + echo 'Installing Inform7 CLI'
      Installing Inform7 CLI
      + cd inform7-6M62/
      + tar xzf inform7-common_6M62_all.tar.gz
      + '[' Linux '!=' Mac ']'
      ++ uname -m
      + ARCH=x86_64
      + tar xzf inform7-compilers_6M62_x86_64.tar.gz
      + tar xzf inform7-interpreters_6M62_x86_64.tar.gz
      + cd ..
      + rm -f inform7-6M62/share/inform7/Internal/I6T/Actions.i6t
      + cp inform7/share/inform7/Internal/I6T/Actions.i6t inform7-6M62/share/inform7/Internal/I6T/Actions.i6t
      + '[' Linux == Mac ']'
      + echo 'Installing cheapglk'
      Installing cheapglk
      + cd glulx/cheapglk
      + make -B
      cc -g -Wall -Werror -std=gnu99    -c -o cgfref.o cgfref.c
      cc -g -Wall -Werror -std=gnu99    -c -o cggestal.o cggestal.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgmisc.o cgmisc.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgstream.o cgstream.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgstyle.o cgstyle.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgwindow.o cgwindow.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgschan.o cgschan.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgdate.o cgdate.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgunicod.o cgunicod.c
      cc -g -Wall -Werror -std=gnu99    -c -o main.o main.c
      cc -g -Wall -Werror -std=gnu99    -c -o gi_dispa.o gi_dispa.c
      cc -g -Wall -Werror -std=gnu99    -c -o gi_blorb.o gi_blorb.c
      cc -g -Wall -Werror -std=gnu99    -c -o gi_debug.o gi_debug.c
      cc -g -Wall -Werror -std=gnu99    -c -o cgblorb.o cgblorb.c
      cc -g -Wall -Werror -std=gnu99    -c -o agent.o agent.c
      ar r libcheapglk.a cgfref.o cggestal.o cgmisc.o cgstream.o cgstyle.o cgwindow.o cgschan.o cgdate.o cgunicod.o main.o gi_dispa.o gi_blorb.o gi_debug.o cgblorb.o agent.o
      ar: creating libcheapglk.a
      ranlib libcheapglk.a
      echo LINKLIBS =   > Make.cheapglk
      echo GLKLIB = -lcheapglk >> Make.cheapglk
      + echo 'Installing git-glulx-ml'
      Installing git-glulx-ml
      + cd glulx/Git-Glulx
      + make -B
      echo "// Automatically generated file -- do not edit!" > version.h
      echo "#define GIT_MAJOR" 1 >> version.h
      echo "#define GIT_MINOR" 3 >> version.h
      echo "#define GIT_PATCH" 5 >> version.h
      cc -O2  -I../cheapglk   -c -o git.o git.c
      cc -O2  -I../cheapglk   -c -o memory.o memory.c
      cc -O2  -I../cheapglk   -c -o compiler.o compiler.c
      cc -O2  -I../cheapglk   -c -o opcodes.o opcodes.c
      cc -O2  -I../cheapglk   -c -o operands.o operands.c
      cc -O2  -I../cheapglk   -c -o peephole.o peephole.c
      cc -O2  -I../cheapglk   -c -o terp.o terp.c
      cc -O2  -I../cheapglk   -c -o glkop.o glkop.c
      cc -O2  -I../cheapglk   -c -o search.o search.c
      cc -O2  -I../cheapglk   -c -o git_unix.o git_unix.c
      cc -O2  -I../cheapglk   -c -o savefile.o savefile.c
      cc -O2  -I../cheapglk   -c -o saveundo.o saveundo.c
      cc -O2  -I../cheapglk   -c -o gestalt.o gestalt.c
      cc -O2  -I../cheapglk   -c -o heap.o heap.c
      cc -O2  -I../cheapglk   -c -o accel.o accel.c
      cc -O2  -o git-glulx-ml git.o memory.o compiler.o opcodes.o operands.o peephole.o terp.o glkop.o search.o git_unix.o savefile.o saveundo.o gestalt.o heap.o accel.o -L../cheapglk -lcheapglk  -lm
      /usr/bin/ld: ../cheapglk/libcheapglk.a(cgfref.o): in function `glk_fileref_does_file_exist':
      /tmp/pip-install-iin97e2z/textworld_e3e1a1d36a5c42b1809d65a0d62f539a/textworld/thirdparty/glulx/cheapglk/cgfref.c:322: undefined reference to `stat'
      collect2: error: ld returned 1 exit status
      make: *** [Makefile:75: git-glulx-ml] Error 1
      Traceback (most recent call last):
        File "/data/zhz_data/anaconda3/envs/agentenv-alfworld/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/zhz_data/anaconda3/envs/agentenv-alfworld/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/zhz_data/anaconda3/envs/agentenv-alfworld/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-jylmgg3_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "<string>", line 37, in run
        File "<string>", line 18, in _pre_install
        File "/data/zhz_data/anaconda3/envs/agentenv-alfworld/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textworld
  Building wheel for visdom (setup.py) ... done
  Created wheel for visdom: filename=visdom-0.2.4-py3-none-any.whl size=1408195 sha256=31b8f71f978f8117c18a33f6f2dcdde21750c2d9c7233f69b46376458c3f5222
  Stored in directory: /home/zhz/.cache/pip/wheels/58/9e/14/30f7cc4dafdd4d602fb00ca33c6edd1424fc0f5df10a02e060
Successfully built visdom
Failed to build textworld
ERROR: Could not build wheels for textworld, which is required to install pyproject.toml-based projects`

**Comment by MarcCote** [comment]
Interesting. I'm planning to drop support for GLK in a future release of TextWorld, that should address this issue. In the meantime, what's OS are you using?

**Comment by MehreenNaeem** [comment]
I also faced the same error while pip install alfworld : (Ubuntu 20.04)
...
building 'glk' extension
      creating build/temp.linux-x86_64-cpython-39/build
      creating build/temp.linux-x86_64-cpython-39/build/temp.linux-x86_64-cpython-39
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/mnaem/alfred_ws/src/alfwd_venv/include -I/usr/include/python3.9 -c build/temp.linux-x86_64-cpython-39/glk.c -o build/temp.linux-x86_64-cpython-39/build/temp.linux-x86_64-cpython-39/glk.o
      build/temp.linux-x86_64-cpython-39/glk.c:50:14: fatal error: pyconfig.h: No such file or directory
         50 | #    include <pyconfig.h>
            |              ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textworld
Failed to build textworld

**Comment by huzican** [comment]
> @huzican Which OS are you using? What's the exact error message?
> 
> @MehreenNaeem somehow I missed the notification for your reply. Make sure you have python dev installed your machine (e.g. `sudo apt install python-dev`).
@MehreenNaeem 
Building wheel for textworld (pyproject.toml)
Traceback (most recent call last):
        File "/mnt/petrelfs/huzican/anaconda3/envs/alfw/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/petrelfs/huzican/anaconda3/envs/alfw/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/petrelfs/huzican/anaconda3/envs/alfw/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 994, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 383, in run
          self.run_command("build")
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 994, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 994, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mivmb85n/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 37, in run
        File "<string>", line 18, in _pre_install
        File "/mnt/petrelfs/huzican/anaconda3/envs/alfw/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 7.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textworld
Failed to build textworld
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (textworld)

The operating system is an Ubuntu 20, and I don't have sudo privileges.

**Comment by MarcCote** [comment]
Can you paste the output of

    pip install -vvv "textworld[pddl]>=1.6.1"

**Comment by MarcCote** [comment]
Just for good measure, can you try to update the pip version and try again:

    pip install -U pip
    pip install -vvv "textworld[pddl]>=1.6.1"

**Comment by MarcCote** [comment]
Also, can you make sure you can download this

     curl -LO http://emshort.com/inform-app-archive/6M62/I7_6M62_Linux_all.tar.gz

**Comment by huzican** [comment]
> Also, can you make sure you can download this
> 
> ```
>  curl -LO http://emshort.com/inform-app-archive/6M62/I7_6M62_Linux_all.tar.gz
> ```
> 
> Because you should get something like:
> 
> ```
>   Downloading Inform7 CLI
>   + curl -LO http://emshort.com/inform-app-archive/6M62/I7_6M62_Linux_all.tar.gz
>     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                    Dload  Upload   Total   Spent    Left  Speed
> 
>     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>     1 22.1M    1  443k    0     0   997k      0  0:00:22 --:--:--  0:00:22  995k
>    29 22.1M   29 6633k    0     0  4640k      0  0:00:04  0:00:01  0:00:03 4639k
>   100 22.1M  100 22.1M    0     0   9.8M      0  0:00:02  0:00:02 --:--:--  9.8M
> ```

After I downloaded this manually, the issue was resolved. Thank you very much for your help!

**Comment by MarcCote** [comment]
Great! Thanks for letting me know. Ideally, I'd like the installation process to be simple. I wonder if this is because of the http instead of https.
