### ISSUE TITLE
If alfworld can't be installed on windows ? There is an error jumping out when I installed it.

### ISSUE THREAD

**Issue by snow-like-kk** [alfworld/alfworld#90]
the error is here:
```
(mllm) C:\Users\29841>pip install alfworld[full]
Collecting alfworld[full]
  Using cached alfworld-0.3.5-py3-none-any.whl.metadata (2.2 kB)
Collecting ai2thor==2.1.0 (from alfworld[full])
  Using cached ai2thor-2.1.0-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting opencv-python (from alfworld[full])
  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting pandas (from alfworld[full])
  Using cached pandas-2.2.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting textworld>=1.6.1 (from textworld[pddl]>=1.6.1->alfworld[full])
  Using cached textworld-1.6.1.tar.gz (708 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torch (from alfworld[full])
  Using cached torch-2.4.1-cp310-cp310-win_amd64.whl.metadata (27 kB)
Collecting torchvision (from alfworld[full])
  Using cached torchvision-0.19.1-cp310-cp310-win_amd64.whl.metadata (6.1 kB)
Requirement already satisfied: tqdm in d:\app\conda\envs\mllm\lib\site-packages (from alfworld[full]) (4.66.5)
Collecting werkzeug==2.0.3 (from alfworld[full])
  Using cached Werkzeug-2.0.3-py3-none-any.whl.metadata (4.5 kB)
Collecting h5py (from alfworld[full])
  Downloading h5py-3.12.1-cp310-cp310-win_amd64.whl.metadata (2.5 kB)
Collecting pycocotools (from alfworld[full])
  Downloading pycocotools-2.0.8-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
Collecting transformers (from alfworld[full])
  Downloading transformers-4.45.2-py3-none-any.whl.metadata (44 kB)
Collecting visdom (from alfworld[full])
  Downloading visdom-0.2.4.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting flask (from ai2thor==2.1.0->alfworld[full])
  Using cached flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting numpy (from ai2thor==2.1.0->alfworld[full])
  Using cached numpy-2.1.2-cp310-cp310-win_amd64.whl.metadata (59 kB)
Requirement already satisfied: pyyaml in d:\app\conda\envs\mllm\lib\site-packages (from ai2thor==2.1.0->alfworld[full]) (6.0.2)
Collecting requests (from ai2thor==2.1.0->alfworld[full])
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting progressbar2 (from ai2thor==2.1.0->alfworld[full])
  Using cached progressbar2-4.5.0-py3-none-any.whl.metadata (16 kB)
Collecting cffi>=1.0.0 (from textworld>=1.6.1->textworld[pddl]>=1.6.1->alfworld[full])
  Using cached cffi-1.17.1-cp310-cp310-win_amd64.whl.metadata (1.6 kB)
Collecting networkx>=2 (from textworld>=1.6.1->textworld[pddl]>=1.6.1->alfworld[full])
  Using cached networkx-3.4.1-py3-none-any.whl.metadata (6.3 kB)
Collecting more-itertools (from textworld>=1.6.1->textworld[pddl]>=1.6.1->alfworld[full])
  Using cached more_itertools-10.5.0-py3-none-any.whl.metadata (36 kB)
Collecting tatsu>=5.8.3 (from textworld>=1.6.1->textworld[pddl]>=1.6.1->alfworld[full])
  Using cached TatSu-5.8.3-py2.py3-none-any.whl.metadata (13 kB)
Collecting hashids>=1.2.0 (from textworld>=1.6.1->textworld[pddl]>=1.6.1->alfworld[full])
  Using cached hashids-1.3.1-py2.py3-none-any.whl.metadata (5.5 kB)
Collecting jericho>=3.0.3 (from textworld>=1.6.1->textworld[pddl]>=1.6.1->alfworld[full])
  Using cached jericho-3.2.1.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\29841\AppData\Local\Temp\pip-install-p58pl82j\jericho_abe8cd9630314aed961dffe1635d93c5\setup.py", line 24, in <module>
          subprocess.check_call(['make', 'clean'], cwd=FROTZPATH)
        File "D:\app\conda\envs\mllm\lib\subprocess.py", line 364, in check_call
          retcode = call(*popenargs, **kwargs)
        File "D:\app\conda\envs\mllm\lib\subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "D:\app\conda\envs\mllm\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\app\conda\envs\mllm\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Jack-Liu0227** [comment]
I have the same problem on windows. Have you solved it?

**Comment by MarcCote** [comment]
ALFWorld doesn't directly support Windows. You can either use Docker (see [Readme](https://github.com/alfworld/alfworld?tab=readme-ov-file#docker-setup)) or WSL2 (see https://github.com/alfworld/alfworld/issues/47).

**Comment by snow-like-kk** [comment]
> I have the same problem on windows. Have you solved it?

No, then I used the romote Ubuntu server, but it doesn't work yet.

**Comment by MarcCote** [comment]
@snow-like-kk can you provide the exact commands and error messages that doesn't work on Ubuntu? Note that you need to enable xserver on remove server, see https://github.com/alfworld/alfworld/issues/65

**Comment by MarcCote** [comment]
@snow-like-kk any update on this?

**Comment by Light7Rain** [comment]
1. Alfworld does not support installation on Windows systems, you should install it on a Linux system, such as Ubuntu 18.04.
2. You might try specifying a different download source when running the pip install command, for example: 
    `pip install alfworld[full] -i https://mirrors.aliyun.com/pypi/simple`, 
    this worked for me.

**Comment by MarcCote** [comment]
I **_strongly_** advise to not use unknown download source and use the official [PyPi](https://pypi.org/). If you have any issue, I'm happy to help with the installation process.
