### ISSUE TITLE
meeting a mistake when run alfworld-play-thor

### ISSUE THREAD

**Issue by Wangzzy52** [alfworld/alfworld#95]
(alfworld) (base) wangjunjian@ubuntu:/data1/wangjunjian/ReAct/alfworld/alfworld$ alfworld-play-thor
Traceback (most recent call last):
  File "/data1/wangjunjian/anaconda/envs/alfworld/bin/alfworld-play-thor", line 107, in <module>
    args.problem = os.path.dirname(random.choice(problems))
  File "/data1/wangjunjian/anaconda/envs/alfworld/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

Can you help me?

**Comment by MarcCote** [comment]
Hi, did you run the `alfworld-download` script? See https://github.com/alfworld/alfworld?tab=readme-ov-file#quickstart
